# Задача 1: сравнение предложений

In [86]:
import re
import numpy as np
from scipy.spatial import distance

# 2.
Каждая строка в файле соответствует одному предложению. Считайте их, приведите каждую к нижнему регистру с помощью строковой функции lower().

In [87]:
file_obj = open('sentences.txt', 'r', encoding='utf-8')
for line in file_obj:
    print(line.lower())
file_obj.close()

in comparison to dogs, cats have not undergone major changes during the domestication process.

as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.

a common interactive use of cat for a single file is to output the content of a file to standard output.

cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.

in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.

the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.

domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).

however, if the output is piped or redirected, cat is unnecessary.

cat with one named file is safer where human error is a concern - one wrong us

# 3.
Произведите токенизацию, то есть разбиение текстов на слова. Для этого можно воспользоваться регулярным выражением, которое считает разделителем любой символ, не являющийся буквой: re.split('[^a-z]', t). Не забудьте удалить пустые слова после разделения.

In [88]:
file_obj = open('sentences.txt', 'r')
a = re.split('[^a-z]', file_obj.read().lower())
type(file_obj.read())
b = ''
b = ';'.join(a)
c = b.split(";")
#print(c)
k = 0
for i in range(len(c)):
    if (c[i-k] == ''):
        del c[i-k]
        k += 1
##print(c)
file_obj.close()

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', 'as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', 'a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', 'cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', 'in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', 'the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that',

# 4.
Составьте список всех слов, встречающихся в предложениях. Сопоставьте каждому слову индекс от нуля до (d - 1), где d — число различных слов в предложениях. Для этого удобно воспользоваться структурой dict.

In [89]:
file_obj = open('sentences.txt', 'r')
a = re.split('[^a-z]', file_obj.read().lower())
type(file_obj.read())
b = ';'.join(a)
c = b.split(";")
#print(c)
k = 0
#удалим пустые слова
for i in range(len(c)):
    if (c[i-k] == ''):
        del c[i-k]
        k += 1
#удалим лишние слова из списка 'c' и получим новый список 'c2', в котором нет повторяющихся слов.
c2 = []
for j in range(len(c)):
    if (j == 0):
        c2.append(c[j])
    else:
        flag = 0
        for i in range(len(c2)):
            if (c[j] == c2[i]):
                flag = 1
            else:
                continue
        if (flag != 1):
            c2.append(c[j])
#print(len(c2))
#создадим из списка 'c2' словарь 'dict_1'
dict_1 = {a: c2[a] for a in range(len(c2))}
##print(dict_1)
file_obj.close()

{0: 'in', 1: 'comparison', 2: 'to', 3: 'dogs', 4: 'cats', 5: 'have', 6: 'not', 7: 'undergone', 8: 'major', 9: 'changes', 10: 'during', 11: 'the', 12: 'domestication', 13: 'process', 14: 'as', 15: 'cat', 16: 'simply', 17: 'catenates', 18: 'streams', 19: 'of', 20: 'bytes', 21: 'it', 22: 'can', 23: 'be', 24: 'also', 25: 'used', 26: 'concatenate', 27: 'binary', 28: 'files', 29: 'where', 30: 'will', 31: 'just', 32: 'sequence', 33: 'a', 34: 'common', 35: 'interactive', 36: 'use', 37: 'for', 38: 'single', 39: 'file', 40: 'is', 41: 'output', 42: 'content', 43: 'standard', 44: 'hear', 45: 'sounds', 46: 'too', 47: 'faint', 48: 'or', 49: 'high', 50: 'frequency', 51: 'human', 52: 'ears', 53: 'such', 54: 'those', 55: 'made', 56: 'by', 57: 'mice', 58: 'and', 59: 'other', 60: 'small', 61: 'animals', 62: 'one', 63: 'people', 64: 'deliberately', 65: 'tamed', 66: 'artificial', 67: 'selection', 68: 'they', 69: 'were', 70: 'useful', 71: 'predators', 72: 'vermin', 73: 'domesticated', 74: 'its', 75: 'closes

# 5.
Создайте матрицу размера n * d, где n — число предложений. Заполните ее: элемент с индексом (i, j) в этой матрице должен быть равен количеству вхождений j-го слова в i-е предложение. У вас должна получиться матрица размера 22 * 254.

In [90]:
file_obj = open('sentences.txt', 'r')
data_list = file_obj.readlines()

#for line in data_list: print(line.strip())
#создаём матрицу размера 22 * 254, заполненную нулями
matrix = np.zeros((len(data_list), len(dict_1)))
for n in range(len(data_list)):
    for m in range(len(dict_1)):
        matrix[n,m] = int(re.split('[^a-z]', data_list[n].lower()).count(dict_1[m]))
#print(matrix)
file_obj.close()

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


# 6.
Найдите косинусное расстояние от предложения в самой первой строке (In comparison to dogs, cats have not undergone...) до всех остальных с помощью функции scipy.spatial.distance.cosine. Какие номера у двух предложений, ближайших к нему по этому расстоянию (строки нумеруются с нуля)? Эти два числа и будут ответами на задание. Само предложение (In comparison to dogs, cats have not undergone... ) имеет индекс 0.

In [92]:
p = []
for n in range(1, len(data_list)):
    p.append(distance.cosine(matrix[0], matrix[n]))
p_2 = sorted(p)
num1 = 0
num2 = 0
for j in range(len(p)):
    if(p_2[0] == p[j]):
        num1 = j+1
    if(p_2[1] == p[j]):
        num2 = j+1

# 7.
Запишите полученные числа в файл, разделив пробелом. Обратите внимание, что файл должен состоять из одной строки, в конце которой не должно быть переноса. Пример файла с решением вы можете найти в конце задания (submission-1.txt).

In [97]:
file_obj = open('file_to_write_1.txt', 'w')
stroka = str(num1) + " " + str(num2)
print(stroka)
stroka = stroka.strip()
file_obj.write(stroka)
file_obj.close()

6 4
